### ISSUE TITLE
Please update glow to v1.2.1

### ISSUE THREAD

**Issue by Hoeze** [conda-forge/glow-feedstock#7]
### Comment:

Dear @kianfar77, would it be possible to automatically publish the latest glow.py releases here?
I currently cannot update to the latest glow version because the PyPI package would break my enviroment by overwriting certain conda packages.

**Comment by henrydavidge** [comment]
@Hoeze Apologies for the long delay. v2.0.0 should be available in conda-forge soon.

**Comment by Hoeze** [comment]
Thanks a lot for the update @henrydavidge!
